### ISSUE TITLE
git push should update origin/master

### ISSUE THREAD

**Issue by pchampin** [onlywei/explain-git-with-d3#50]
try the following:
```
git commit
git fetch
git merge origin/master
git push
```
after the push, the branch `origin/master` has not been updated from its position got after the fetch, which is not consistent with how git actually works (it should end up on the same commit as master).

**Comment by kheyse-oqton** [comment]
Seems to work for me.

**Comment by kheyse-oqton** [comment]
Duplicate of #19 ?

**Comment by pchampin** [comment]
Indeed, it is a duplicate.

**Comment by waldyrious** [comment]
> Indeed, it is a duplicate.

Any reason not to close this, then?
